--- 
- 
  apt_repository: "repo=\"ppa:ondrej/php\" update_cache=yes"
  name: "Adding PHP repository for PHP 7.1"
- 
  apt: 
    force: true
    name: php*
    purge: true
    state: absent
  name: "Purging all other PHP version packages."
  register: php_version_purge
- 
  apt: 
    force: true
    name: php-common
    purge: true
    state: absent
  name: "Ensuring any Extrneous PHP packages are removed"
  when: "php_version_purge.changed | bool"
- 
  apt: 
    name: 
      - php7.1-zip
      - php7.1-xsl
      - php7.1-xmlrpc
      - php7.1-xml
      - php7.1-tidy
      - php7.1-sybase
      - php7.1-soap
      - php7.1-readline
      - php7.1-pspell
      - php7.1-pgsql
      - php7.1-opcache
      - php7.1-odbc
      - php7.1-mysql
      - php7.1-sqlite3
      - php7.1-ldap
      - php7.1-mbstring
      - php7.1-json
      - php7.1-intl
      - php7.1-imap
      - php7.1-gmp
      - php7.1-gd
      - php7.1-fpm
      - php7.1-dev
      - php7.1-dba
      - php7.1-curl
      - php7.1-common
      - php7.1-cli
      - php7.1-cgi
      - php7.1-bz2
      - php7.1-bcmath
      - php7.1-interbase
      - php7.1-pdo-firebird
      - php7.1-fileinfo
      - php7.1-exif
      - php7.1-apcu
      - composer
  name: "Update all packages to the latest version"
- 
  become: true
  name: "Setting up php-fpm"
  notify: 
    - "restart nginx"
  replace: "dest=/etc/php/7.1/fpm/php.ini regexp=\"(;cgi.fix_pathinfo=1)\" replace=\"cgi.fix_pathinfo=0\""
- 
  become: true
  name: "Setting PHP timezone"
  replace: "dest=/etc/php/7.1/fpm/php.ini regexp=\"(;date.timezone =)\" replace=\"date.timezone=America/New_York\""
- 
  become: true
  name: "Setting Allowed Upload size"
  replace: "dest=/etc/php/7.1/fpm/php.ini regexp=\"(upload_max_filesize = 2M)\" replace=\"upload_max_filesize = 0\""
- 
  become: true
  name: "Setting Post Max size"
  replace: "dest=/etc/php/7.1/fpm/php.ini regexp=\"(post_max_size = 8M)\" replace=\"post_max_size = 0\""
- 
  become: true
  name: "Adding php settings"
  notify: 
    - "restart nginx"
  template: "src=../../nginx/templates/nginx-docova-common.conf dest=/etc/nginx/nginx-docova-common.conf owner=www-data group=www-data mode=0644"
