--- 
- 
  apt: 
    update_cache: true
- 
  get_url: 
    dest: /tmp/phpMyAdmin.zip
    url: "https://files.phpmyadmin.net/phpMyAdmin/5.0.3/phpMyAdmin-5.0.3-all-languages.zip"
  name: "Copying phpMyAdmin Zip"
- 
  become: true
  name: "Extract phpMyAdmin"
  unarchive: 
    dest: /tmp
    group: www-data
    owner: www-data
    remote_src: true
    src: /tmp/phpMyAdmin.zip
- 
  become: true
  command: "mv /tmp/phpMyAdmin-5.0.3-all-languages /usr/share/phpmyadmin"
  name: "Move phpMyAdmin install files"
- 
  changed_when: false
  name: "check if nginx is installed"
  register: nginx_conf_dir
  stat: 
    path: /etc/nginx/conf.d
- 
  file: 
    path: /etc/nginx/global.d
    state: directory
  name: "ensure directory for global nginx configuration files exists"
  when: nginx_conf_dir.stat.exists
- 
  name: "ensure phpmyadmin configuration for nginx is installed"
  notify: "restart nginx"
  template: 
    dest: /etc/nginx/global.d/phpmyadmin.conf
    src: nginx.conf.j2
  when: nginx_conf_dir.stat.exists
